# Generated by Django 2.1.dev20170216045417 on 2018-04-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestream', '0004_auto_20180414_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='time',
            field=models.DateTimeField(null=True, verbose_name='date published'),
        ),
    ]
